### ISSUE TITLE
Error detection, error first convention?

### ISSUE THREAD

**Issue by jeffandersen** [whatadewitt/yfsapi#1]
I would expect error handling to be supported at the module level, otherwise I end up having to wrap the module myself just to add a simple `if (data.error)` to each callback.

```js
// query a resource/subresource
yf.{resource}.{subresource} (
  {possible argument(s)},
  function cb(err, data) {
    // handle an error
    if (err) {
      console.error(err);
    }
    // do your thing
  }
);
```

**Comment by whatadewitt** [comment]
It's been a while, but I've finally started on this! Hopefully will have some updates up soon, been tough since the baby came :D
