### ISSUE TITLE
Selected Position / Status Question

### ISSUE THREAD

**Issue by whatadewitt** [whatadewitt/yfsapi#11]
Hi @ryus08,

Making some changes to the Roster resource and I notice that the PR you submitted sends back coverage type and date along with what we're really interested in... you cool if I simplify that?

--d

**Comment by whatadewitt** [comment]
(had no other idea how to contact you)

**Comment by ryus08** [comment]
If by simplify you mean "make the object easier to use" absolutely. If you want to ditch exposing the info at all, I wouldn't be particularly psyched. But those two params should be in the request anyways (unless it is "today"), so  the user should already know the info anyways.

So cool with me.

**Comment by whatadewitt** [comment]
Just pushed the update. Let me know if you see any issues! Thanks!!
