### ISSUE TITLE
Selected_position field

### ISSUE THREAD

**Issue by nmichaud2** [whatadewitt/yfsapi#12]
I am making calls using the roster function of TeamResource and all roster players have their select_position and starting_status field empty. I'm guessing it's an error on yahoo's side but I was wondering if you ever encountered this issue before ?

**Comment by whatadewitt** [comment]
Very strange... I can query my league and get the proper data...

357.l.16987.t.1

What version of the API are you on?

**Comment by nmichaud2** [comment]
I had 0.4.1. Just got 0.4.3 and it works fine for the selected_position !

**Comment by whatadewitt** [comment]
Great! I made some changes in 0.4.2 when I saw some inconsistencies! Glad it's being used :D
