### ISSUE TITLE
week option not working

### ISSUE THREAD

**Issue by mehtaculous** [whatadewitt/yfsapi#16]
The week option seems to work for the [online module](http://yfantasysandbox.herokuapp.com/resource/player/stats), but when I enter a week value for my function, the API call just ignores it and returns the data for season long statistics instead. Is there something that I am doing incorrect?
```
var player_key = '331.p.7200';
var week = '2';

yf.player.stats(
    player_key,
    week,
    function cb(err, data) {
        if (err) {
            console.log(err);
        }    
        console.log(player_key);
        console.log(week);
        console.log(JSON.stringify(data));
    }
);
```

**Comment by withsmilo** [comment]
Please check that your yfsapi module is updated to v0.5.2 or not.

**Comment by mehtaculous** [comment]
I guess that was the issue..it works now. Thanks!
