### ISSUE TITLE
Opponent Names for Football

### ISSUE THREAD

**Issue by mehtaculous** [whatadewitt/yfsapi#18]
Which resource would I have to use to find out opponent names for weekly nfl player stats?

**Comment by charlietfl** [comment]
I couldn't find anything in Yahoo API that provides the nfl game info. I found this resource  http://www.nfl.com/ajax/scorestrip?season=2016&seasonType=REG&week=5.

Haven't found any docs for that API either.
It returns xml and I haven't figured out how to set it to return json but it is also CORS enabled. I ended up looping through every week and storing the data myself then matching it to players as needed

**Comment by whatadewitt** [comment]
I think this data comes from Sports, not Fantasy Sports, which isn't open, unfortunately...
