### ISSUE TITLE
teamHelper mapTeams issue

### ISSUE THREAD

**Issue by Adamrzw** [whatadewitt/yfsapi#21]
Map Teams is failing in 1.0.0.  

Line 17: destinationObj[key] = _.isobj[key];

Should be:

destinationObj[key] = _.isObject(key); 

:)

**Comment by whatadewitt** [comment]
It's so weird that when I tested the function it was working, but I probably ran an undo or something and didn't check close enough when I merged.

I'm at work now, I will fix this tonight when I get home. Sorry about that!

**Comment by Adamrzw** [comment]
No problem, glad to help. This module is still seriously helping me by taking care of all that OAuth business and wacky yahoo data structure. 

 But looking at the code further, I think you really meant just obj[key] to map the property, not the _.isObject(key) to see if its an object, right?

**Comment by whatadewitt** [comment]
You're correct and the fix has been pushed to NPM!

Thanks!
