### ISSUE TITLE
Request: include REST query in the demo

### ISSUE THREAD

**Issue by philip** [whatadewitt/yfsapi#25]
Please print the REST query in the demo's output under "How To Use" so we can generate the output ourselves (without the app). Currently it only displays yfsapi code. 

For example: 
  http://yfantasysandbox.herokuapp.com/resource/league/scoreboard

Granted the above does refer to this:
  http://fantasysports.yahooapis.com/fantasy/v2/league/{league_key}/{sub_resource}

This is a feature request to include attributes we enter, which is "league_key" and optionally "week" on that page. This way we can test the executed REST query ourselves.

**Comment by philip** [comment]
Sorry for not looking at the code before posting this confusing request.

tl;dr version: consider printing "url" somewhere on each page, perhaps under "How To Use".

**Comment by whatadewitt** [comment]
You mean on my fantasy sandbox app? Where in particular? In the writeups at the top of most pages I have a note that says

"maps to http://fantasysports.yahooapis.com/fantasy/v2/team/{team_key}/{sub_resource}"

... although those should probably be listed as HTTPS now...

**Comment by philip** [comment]
Ah yes, sorry for mixing up the sandbox and library. But while we're here, I'm referring to the executed query, such as:

http://fantasysports.yahooapis.com/fantasy/v2/league/123.l.4567/scoreboard;week=15?format=json

My use case is to use your sandbox to generate (and figure out) URLs for my own code, although perhaps folks will also be curious what the executed REST query looks like.

Consider adding that directly under "Sample Output" right above the JSON, or elsewhere.
