### ISSUE TITLE
Documentation - roster resource incorrect

### ISSUE THREAD

**Issue by kmudrick** [whatadewitt/yfsapi#27]
It looks like the arguments to the roster resource are team key, then date:

https://github.com/whatadewitt/yfsapi/blob/master/resources/rosterResource.js#L9

But the documentation has an example with that reversed:

http://yfantasysandbox.herokuapp.com/resource/roster/players

![image](https://cloud.githubusercontent.com/assets/204913/20614137/1366639e-b299-11e6-8867-f717c85d34a4.png)

**Comment by whatadewitt** [comment]
This should be fixed now.
