### ISSUE TITLE
Roster player mappings missing

### ISSUE THREAD

**Issue by ryus08** [whatadewitt/yfsapi#3]
First, love the wrapper. Real sleek. Way to hide that nasty model they expose.

When I got the roster players resource, I noticed that it was missing a few things I expected, namely:

* selected_position
* starting_status
* is_editable
* image_url

Looks like when the library flattens the sub-objects under player, it misses those first three fields. Additionally, it only takes the first property on each sub-object (so something like image_url is missed).

So, player looks like this out of yahoo's endpoint:
```
"player": [
  [{
      "player_key": "357.p.8578"
    }, {
      "player_id": "8578"
    }, {
      "name": {
        "full": "Buster Posey",
        "first": "Buster",
        "last": "Posey",
        "ascii_first": "Buster",
        "ascii_last": "Posey"
      }
    },
  ...
       {
      "headshot": {
        "url": "http://l.yimg.com/iu/api/res/1.2/gfBnDzOC0vzY92FGzMlqrA--/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/20160401/8578.png",
        "size": "small"
      },
      "image_url": "http://l.yimg.com/iu/api/res/1.2/gfBnDzOC0vzY92FGzMlqrA--/YXBwaWQ9c2hhcmVkO2NoPTIzMzY7Y3I9MTtjdz0xNzkwO2R4PTg1NztkeT0wO2ZpPXVsY3JvcDtoPTYwO3E9MTAwO3c9NDY-/https://s.yimg.com/xe/i/us/sp/v/mlb_cutout/players_l/20160401/8578.png"
    },
  ...
       {
      "has_player_notes": 1
    },
    []
  ], {
    "selected_position": [{
      "coverage_type": "date",
      "date": "2016-04-10"
    }, {
      "position": "C"
    }]
  }, {
    "starting_status": [{
      "coverage_type": "date",
      "date": "2016-04-10"
    }, {
      "is_starting": 1
    }]
  }, {
    "is_editable": 1
  }
]
```

So the player object is an array, and only the objects in its first index are flattened into the result, missing selected_position, starting_status, and is_editable. And notice that image_url is the second property in a flattenned object, so it is missed.

I forked your repo and I believe have a fix for the [first issue](https://github.com/ryus08/yfsapi/pull/2), [second issue](https://github.com/ryus08/yfsapi/pull/3/files), and [better mapping](https://github.com/ryus08/yfsapi/pull/4/files) for selected_position, starting_status, and is_editable.

Any interest in me filing a PR to your repo?

**Comment by whatadewitt** [comment]
Hey @ryus08,

That would be great! I'm pretty slammed at work this week, but I would love a PR to fix these issues! I'll try to get to it in the free time I can find!

Thanks!!

--d

**Comment by ryus08** [comment]
Cool, I'll file it tomorrow. 

One last thing, I'd gladly add a test, but I don't see them anywhere. I do see some Downloading your npm package.

If you point me to them, I'll add one. 

No rush.

**Comment by whatadewitt** [comment]
I'm actually working on these in the little free time that I have right now. For now, don't worry about it (awful to say, I know)

**Comment by ryus08** [comment]
Ha, no judgement. If you want a hand, let me know.
