### ISSUE TITLE
Search subresource not working?

### ISSUE THREAD

**Issue by bflopez** [whatadewitt/yfsapi#35]
When I put in something in the search field on 
    http://yfantasysandbox.herokuapp.com/collection/players/leagues
it does not make a difference. Is this a problem with the API or the node module?

**Comment by whatadewitt** [comment]
Just verifying... you are logged in... right?

**Comment by bflopez** [comment]
Yep logged in. I assume its the yahoo API not working correctly but not sure.

**Comment by whatadewitt** [comment]
This indeed is a bug. Mentioned what I'm doing on the other thread... should be fixed tonight...

**Comment by whatadewitt** [comment]
... oh jesus... the API isn't broken... my damn sandbox app has "seach" as the subresource name instead of "search"... so it should be working... just not in my sandbox...

**Comment by bflopez** [comment]
Haha alright sounds good! I have been working off your sandbox. I git cloned it and have been hacking at it understanding the API itself.

**Comment by whatadewitt** [comment]
That's it's intended purpose, but I did write it a few years ago, so it may not be ideal! Glad to see it's being used! Reach out if there are any questions!
