### ISSUE TITLE
bearer_token_not_over_ssl

### ISSUE THREAD

**Issue by tells** [whatadewitt/yfsapi#37]
Seeing this 401 when trying get any sort of info after authenticating.  I've logged in a couple of times, refreshed the token, used other accounts.  Can't seem to use any of the API.  OAuth 1.0 seems to work on FantasyPros.  Wondering what might be causing the issue.

```
{
  "lang": "en-US",
  "description": "Please provide valid credentials. OAuth oauth_problem=\"bearer_token_not_over_ssl\", realm=\"yahooapis.com\""
}
```

**Comment by almartin82** [comment]
Hi @tells, seeing this too.  [This](https://stackoverflow.com/questions/46091560/yahoo-oauth-2-0-bearer-token-not-over-ssl-explain) SO question says that this is server side / ephemeral.  Is that what you experienced?

**Comment by almartin82** [comment]
ah, nevermind.  updated all my urls from `http` to `https` and this went away.  thanks!
