### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by isaac2004** [whatadewitt/yfsapi#38]
As of 9:22 EST 9/20/2017

**Comment by whatadewitt** [comment]
Which site, specifically?

**Comment by isaac2004** [comment]
The herokuapp was down.. Looks back up now

**Comment by isaac2004** [comment]
actually @whatadewitt I see what the issue is. Fetching [team collection](http://yfantasysandbox.herokuapp.com/collection/teams/fetch) is failing when stats is checked

**Comment by whatadewitt** [comment]
Hmmm... I am able to run without issue...

Here's a screenshot...

![screenshot 2017-09-20 15 12 15](https://user-images.githubusercontent.com/363730/30660104-29ac06f4-9e16-11e7-9752-d60ce1d03411.png)

**Comment by isaac2004** [comment]
Yea it is weird, I think it might be the Yahoo Api is temperamental. I had a question about how you are parsing the horrible json from the Api. What is the best way to chat if you have time?

**Comment by whatadewitt** [comment]
haha parsing it with a lot of maps and trial and error...

I don't know if GitHub has an email or DM feature, but if it does, reach out to me through that and I will let you know. I'm also on twitter @whatadewitt
