### ISSUE TITLE
Request: get all user's leagues and teams, both past and present

### ISSUE THREAD

**Issue by philip** [whatadewitt/yfsapi#39]
This feature request answers the following question:

  "Which leagues does a user belong in, both past and present?"

The idea is related to game_leagues and game_teams. For example, going here:

  http://yfantasysandbox.herokuapp.com/resource/user/game_leagues

It could then list all Yahoo leagues a user was or is in, and by default include all types such as baseball, football, and so on.

Filtering options might include: year (or similar) and/or type (e.g., nfl).

Returned values might include: `{game_key}.l.{league_key}` for leagues or `{game_key}.l.{league_key}.t.{team_key}` for teams.

If this is already possible then an example code snippet would be great :)

**Comment by philip** [comment]
Sorry, I overlooked this. This ability is listed under resource/user/games and not resource/user/game_leagues.  Sorry for the noise :)

**Comment by whatadewitt** [comment]
No worries! Sorry I haven't been able to respond! Been quite busy at work recently!
