### ISSUE TITLE
jquery 404 on heroku app

### ISSUE THREAD

**Issue by foldedpaper** [whatadewitt/yfsapi#40]
Hello, I like to use your very helpful heroku app as an example to check against when I am noodling around with my own API-accessing code. But I am having trouble with the site--it seems that jquery is not loading.

When I check developer console, 

`http://yfantasysandbox.herokuapp.com/collection/teams/javascripts/vendor/jquery-1.10.2.min.js`

returns

`404 Not Found`

**Comment by foldedpaper** [comment]
Okay, a little bit more information here. I see that in Firefox, when trying to load the page, console shows these errors:

'Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://code.jquery.com/jquery-2.2.3.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
None of the “sha256” hashes in the integrity attribute match the content of the subresource.'

**Comment by whatadewitt** [comment]
weird... that resource is requested on all pages... and you're only seeing it on the "Teams Collection" page?

**Comment by foldedpaper** [comment]
No, sorry--it happens on each page of the site. I really botched the initial report, and have been figuring out more as I go.

**Comment by foldedpaper** [comment]
Aha, figured out the issue here after resolving a similar issue on another site. Turns out I had a Firefox add-on that was blocking the Google Analytics tracker. That caused the failure to load jquery, too. When Google Analytics tracker is not blocked, the heroku app works as it always has.
