### ISSUE TITLE
Support for Promises

### ISSUE THREAD

**Issue by ryus08** [whatadewitt/yfsapi#41]
In the spirit of ES6/ES8, support for async functions returning a Promise would be awesome. It could be made backwards compatible by only doing so if no callback is provided, and invoking the callback instead if one is.

Do you feel this is worthwhile to add? Considering the variable-argument-length nature of most of the functions, we'd probably need to check if the last parameter is a function and invoke it as a callback if it is.

**Comment by whatadewitt** [comment]
I really like it... be a good opportunity to learn how to build out APIs
this way too and probably isn’t that difficult.

I’ll look into it and perhaps throw it in there for the next release!

**Comment by ryus08** [comment]
I'd gladly take a stab at it too!

**Comment by whatadewitt** [comment]
That’d be great!

**Comment by calder12** [comment]
Hi, any progress on the promises? Maybe I'm missing something but I am struggling a bit here. I can get a list of players and output that nicely, but it seems to me it requires another request for each player to get their stats?

Basically what I want to do is return a roster with all the players stats attached and I'm struggling to do that. Any ideas?

**Comment by whatadewitt** [comment]
Honestly, hoping to hear back from @ryus08 with the comments I left. Otherwise, I may just merge it in if there's enough interest!

As for your question, I think you can accomplish what you're looking for by using the "Team Players" Collection with the "Stats" subresource selected: http://yfantasysandbox.herokuapp.com/collection/players/teams

You can run a test there, but I **THINK** that should give you everything you need.

**Comment by ryus08** [comment]
I'm sorry @whatadewitt I really thought I replied to all your comments, but I see two couple that I hadn't. I believe I have now.

I think to address what I think is your [largest concern](https://github.com/whatadewitt/yfsapi/pull/44/files#r193497229), I need you to pick Option 1 or 2. I know you were [leaning option 2](https://github.com/whatadewitt/yfsapi/pull/45#issuecomment-395148501), but I need to understand if that leaning outweighs your concerns in [that comment](https://github.com/whatadewitt/yfsapi/pull/44/files#r193497229), which I think option 2 provides the best solution for. 

I'll gladly fix those merge conflicts, along with [this suggestion](https://github.com/whatadewitt/yfsapi/pull/44#discussion_r193492072), but I want to know I'm doing it in the version that solves the other concern best.

**Comment by whatadewitt** [comment]
Hey hey! Good to hear from you!
I know originally I was looking at 2, but I think that, looking at it closer (albeit a couple of months ago), 1 may be the more "standard" approach... Of course, it's been a while so I'll try to review tonight...

**Comment by whatadewitt** [comment]
... so ya... number 1 looks better to me... my only gripe is really non-founded on the fact that I'd love to find a way to simplify how many times "extractCallbacks" is needed, but that can certainly wait for another time!

Thanks for checking back in on this! Appreciate the work!

**Comment by ryus08** [comment]
OK closed number 2, rebased number 1, addressed your two comments regarding coalescing the error in the callback in YahooFantasy.mjs and reducing the amount of `Promise.then(...)` chaining everywhere. Let me know if there was something else you'd like addressed.

Tests pass. I made a [subsequent branch](https://github.com/ryus08/yfsapi/pull/10) with TravisCI.org configured and a passing build in my fork if that is helpful

Yeah, I agree about the abundance of `extractCallbacks` calls, but it is tough to remove them with an arbitrary argument list. Could change all the functions to read from the front of the argument list, and stop if it finds a function instead of an optional argument. I think that is pretty much the same as calling extractCallbacks, just from the other side of the list.

Changing the function signatures to accept an object with [named parameters](https://nrempel.com/posts/nodejs-named-parameters/) would make it much easier, callback would always be the second argument, but that is a very breaking change and I believe requires ES6.

**Comment by whatadewitt** [comment]
so... this is pretty awesome :D

I'm going to pull this down, do a bit of playing, but I think all that's left to do is merge, bump the package number and deploy!
