### ISSUE TITLE
Get All Players in League?

### ISSUE THREAD

**Issue by dbalders** [whatadewitt/yfsapi#47]
Hello,

Sorry if this is obvious, but is it possible to get a list of all the players in the league? That way you could make a list of who the free agents are and what not? I couldn't get anything I tried to work and didn't see an option for this in the /resources/ code.

Thanks for the help, loving the tool so far.

**Comment by whatadewitt** [comment]
Unfortunately, no.

The best I've seen is that you can grab Free Agents using the 'league players' collection and you'd have to grab them page-by-page until you have them all (currently it's limited to a max of 25 at a time, I believe). There may be a way to do what you're asking, unfortunately, Yahoo! hasn't made that public.

**Comment by dbalders** [comment]
Ah, kk thanks!
