### ISSUE TITLE
Get failed FAAB bids?

### ISSUE THREAD

**Issue by haz-q** [whatadewitt/yfsapi#48]
In my NFL league, we have a FAAB budget, and the winning and losing bids are shown in the Transactions page after they have processed. The Transactions API seems limited in that only the winning bidder's `faab_bid` is shown. Is there a way to obtain the losing bids as well?

**Comment by whatadewitt** [comment]
Unfortunately, I don't think Yahoo! gives that publicly :(

**Comment by pwidds22** [comment]
@whatadewitt do you know if there has been any update to this by yahoo? or still not possible to get the losing bids ?

**Comment by whatadewitt** [comment]
I've actually been working on some updates to this lately but haven't seen anything, sorry! I will take another look tonight though.

**Comment by pwidds22** [comment]
thanks, appreciate all your work!

**Comment by whatadewitt** [comment]
Tried circumventing some stuff and unfortunately it didn't pan out 🤣 

I am seeing my friend who is friends with someone at Yahoo! tomorrow. I will try to prod them 🤣 

Thanks for playing with it.

--d
