### ISSUE TITLE
[Discussions] Add new APIs to add/drop players

### ISSUE THREAD

**Issue by githubsmilo** [whatadewitt/yfsapi#6]
We need to use [POST http request](https://developer.yahoo.com/fantasysports/guide/#post). 
How about do you add these APIs?

**Comment by whatadewitt** [comment]
I'm working on some of these in the very little spare time I have. 

Adding them wouldn't be much different from what I have, just need to POST the proper data set to the endpoint on the Yahoo! server. Feel free to take a crack at it and submit a PR, or if you're comfortable waiting, I'll get to it eventually :)

**Comment by ryus08** [comment]
I believe I have a branch in place that implements the PUT to update a roster. The transactions resource to POST an add/drop should be similar. I could take a crack at it.

**Comment by githubsmilo** [comment]
@whatadewitt @ryus08 
I completed to implement below new add/drop player APIs. 😃  [(commit link)](https://github.com/githubsmilo/yfsapi-without-auth/commit/3861070f713e5af62e17e819216dc7e670f43e16)
I had the success to test three APIs.

* transactions.add_player(..)
* transactions.drop_player(..)
* transactions.adddrop_players(..)

Changes are here.

* [Rename previous `api` function to `callGetRequest`](https://github.com/githubsmilo/yfsapi-without-auth/commit/3861070f713e5af62e17e819216dc7e670f43e16#diff-168726dbe96b3ce427e7fedce31bb0bcR187). This function has the responsibility to call GET request.
* [Add new `callPostRequest` function](https://github.com/githubsmilo/yfsapi-without-auth/commit/3861070f713e5af62e17e819216dc7e670f43e16#diff-168726dbe96b3ce427e7fedce31bb0bcR215). This function has the responsibility to call POST request.
* [Implement add_player(), drop_player(), adddrop_players() APIs](https://github.com/githubsmilo/yfsapi-without-auth/commit/3861070f713e5af62e17e819216dc7e670f43e16#diff-61b670b7701d6abf7bcea63a2e779955R82).

But, I cannot create a pull request because my work is based on #5 pull request.

**Comment by whatadewitt** [comment]
@githubsmilo I'll take a look and see if I can get this built into what I'm working on... I generally think I'd rather keep using the API call and pass the method along inside the call...

**Comment by githubsmilo** [comment]
@whatadewitt 
Great idea! I will follow you.
